version: '3'
services:
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: nisevi
      POSTGRES_PASSWORD: nisevi*1234
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.2.10
    volumes:
      - redis:/var/lib/redis/data

  nisevi:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/nisevi
    env_file:
      - .env

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/nisevi
    env_file:
      - .env

volumes:
  redis:
  postgres: