source 'https://rubygems.org'
ruby '2.4.0'

gem 'rails', '~> 5.0.1'
gem 'pg', '~> 0.18.4'
gem 'aws-sdk-rails'
gem 'coffee-rails'
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass', '~> 3.3', '>= 3.3.6'
gem 'uglifier', '>= 1.3.0'
gem 'therubyracer', '~> 0.12.2'
gem 'jquery-rails'
gem 'font-awesome-sass'
gem 'humanize'
gem 'haml', '~> 4.0', '>= 4.0.7'
gem 'rmagick'
gem 'kaminari', git: 'https://github.com/amatsuda/kaminari', branch: 'master' #https://github.com/amatsuda/kaminari/issues/44
gem 'sidekiq', '~> 4.1'
gem 'paperclip', '~> 5.0.0'
gem 'ckeditor'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'google-analytics-rails', '1.1.0'
gem 'elasticsearch'
gem 'elasticsearch-model'
gem 'elasticsearch-rails'
gem 'elasticsearch-persistence'
gem 'omniauth-oauth2', '~> 1.3.1'
gem 'devise'
gem 'omniauth-github'
gem 'omniauth-linkedin-oauth2'
gem 'pundit'
gem 'rack-cors'

group :development, :test do
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'rspec-rails', '~> 3.0'
  gem 'factory_girl_rails'
  gem 'faker', '~> 1.6', '>= 1.6.3'
  gem 'annotate', '~> 2.7', '>= 2.7.1'
end

gem 'spring', group: :development
