source 'https://rubygems.org'
ruby '2.4.2'

gem 'rails', '~> 5.1', '>= 5.1.4'
gem 'pg'
gem 'aws-sdk-rails'
gem 'coffee-rails'
gem 'sass-rails'
gem 'bootstrap-sass'
gem 'uglifier'
gem 'therubyracer'
gem 'jquery-rails'
gem 'font-awesome-sass'
gem 'humanize'
gem 'haml'
gem 'kaminari', git: 'https://github.com/amatsuda/kaminari', branch: 'master' #https://github.com/amatsuda/kaminari/issues/44
gem 'recaptcha', require: 'recaptcha/rails'
gem 'omniauth-oauth2'
gem 'devise'
gem 'omniauth-github'
gem 'omniauth-linkedin-oauth2'
gem 'pundit'
gem 'rack-cors'

group :development, :test do
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'rspec-rails'
  gem 'rspec_junit_formatter'
  gem 'factory_bot'
  gem 'faker'
  gem 'annotate'
  gem 'simplecov'
  gem 'spring'
end