development:
  url: <%= ENV['DB_URL'].gsub('?', '_development?') %>

test:
  url: <%= ENV['DB_URL'].gsub('?', '_test?') %>

stagign:
  url: <%= ENV['DB_URL'].gsub('?', '_staging?') %>

production:
  url: <%= ENV['DB_URL'].gsub('?', '_production?') %>

