default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DATABASE_USER_DEV'] %>
  password: <%= ENV['DATABASE_PASS_DEV'] %>
  host: localhost

development:
  <<: *default
  database: <%= ENV['DATABASE_DEVELOPMENT_NAME'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_TEST_NAME'] %>

production:
  <<: *default
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>
  database: <%= ENV['DATABASE_PRODUCTION_NAME'] %>

