default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  url: <%= "#{ENV['DATABASE_URL']}_development" %>

test:
  <<: *default
  url: <%= "#{ENV['DATABASE_URL']}_test" %>

stagign:
  <<: *default
  url: <%= "#{ENV['DATABASE_URL']}_staging" %>

production:
  <<: *default
  url: <%= "#{ENV['DATABASE_URL']}_production" %>

